#!/usr/bin/env groovy

pipeline {
    agent none
    stages {
         stage('Test On Linux') {
              agent {
                        label "linux"
                    }
              steps {
                        echo 'run-tests.sh'
                    }
               post {
                        always {
                            echo 'In post of linux'
                        }
                    }
                }
            }
        }
