#!/usr/bin/env groovy

pipeline {
    agent {
        label 'linux'
    }
    stages {
        stage('Generate Build') {
              steps {
                        cd '${WORKSPACE}'
                        touch 'abcdeg.abcd'
                        echo 'Generate Build Here'
                    }
                }
        
        stage('Upload Build') {
              steps {
                        echo 'Upload build to common repository'
                    }
                }
        
        stage('Deploy Build') {
              steps {
                        echo 'Deploy build to test machine'
                    }
                }

        stage('Run Tests') {
              steps {
                        echo 'Running Unit Tests'
                    }
               post {
                        always {
                            echo 'Generate Report Here'
                        }
                    }
                }
        
            }
        }
