#!/usr/bin/env groovy

pipeline {
    agent none
    stages {
         stage('Test On Windows') {
              agent {
                        label "windows"
                    }
              steps {
                        echo 'Run tests for windows'
                    }
               post {
                        always {
                            echo 'In post of windows'
                        }
                    }
                }
            }
}
